packages:
  - github.com/graniticio/granitic/v2/ws/handler
  - bookapi/endpoint/book

components:

  getBookLogic:
    type: book.GetBookLogic

  getBookHandler:
    type: handler.WsHandler
    HTTPMethod: GET
    Logic: ref:getBookLogic
    PathPattern: "^/books"
