packages:
  - github.com/graniticio/granitic/v2/ws/handler
  - bookapi/endpoint/book

components:

  getBookLogic:
    type: book.GetBookLogic

  getBookHandler:
    type: handler.WsHandler
    HTTPMethod: GET
    Logic: ref:getBookLogic
    PathPattern: "^/books"

  addBookLogic:
    type: book.AddBookLogic

  addBookHandler:
    type: handler.WsHandler
    HTTPMethod: POST
    Logic: ref:addBookLogic
    PathPattern: "^/books"