packages:
  - github.com/graniticio/granitic/v2/ws/handler
  - github.com/graniticio/granitic/v2/validate
  - bookapi/endpoint/book

components:

  getBookLogic:
    type: book.GetBookLogic

  getBookHandler:
    type: handler.WsHandler
    HTTPMethod: GET
    Logic: ref:getBookLogic
    PathPattern: "^/books"

  addBookValidator:
    type: validate.RuleValidator
    Rules: conf:createBookRules
  addBookLogic:
    type: book.AddBookLogic
  addBookHandler:
    type: handler.WsHandler
    HTTPMethod: POST
    Logic: ref:addBookLogic
    PathPattern: "^/books"
    AutoValidator: ref:addBookValidator